### ISSUE TITLE
getPayments() не поддерживает параметры captured_at.* и payment_method

### ISSUE THREAD

**Issue by versusbassz** [yoomoney/yandex-checkout-sdk-php#124]
Метод: \YandexCheckout\Client::getPayments()
Маппинг: \YandexCheckout\Request\Payments\PaymentsRequestSerializer::$propertyMap
Endpoint в API: https://kassa.yandex.ru/developers/api?lang=bash#get_payments_list

Не обрабатываются параметры:
- captured_at.gte
- captured_at.gt
- captured_at.lte
- captured_at.lt
- payment_method

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, подготовим исправление!

**Comment by ostulov** [comment]
Добавлено в v1.6.8
