### ISSUE TITLE
Когда планируется смена урла?

### ISSUE THREAD

**Issue by shmidtelson** [yoomoney/yandex-checkout-sdk-php#128]
Речь об этой настройке 
https://github.com/yoomoney/yandex-checkout-sdk-php/blob/798ac4d08314188d6f237fde99bfa761386fa9ab/lib/configuration.json#L2

**Comment by ostulov** [comment]
Добрый день!

Замена адресов на новые будет произведена в ближайшие рабочие дни.

**Comment by bethrezen** [comment]
> Добрый день!
> 
> Замена адресов на новые будет произведена в ближайшие рабочие дни.

Ну вы бы тогда не закрывали тикет, пока не поменяете адреса то со всеми параметрами...
Письмо всем разослали, а в пакете без изменений пока что
